### ISSUE TITLE
Consider adding a forum/chat?

### ISSUE THREAD

**Issue by matklad** [DataDog/scipio#126] opened 2020-10-19 07:56 UTC
If we intend to grow community around scipo, we would nee some community-space chat-like thing eventually. If we'll need it eventually, we might want to setup it sooner rather than later, because why not? Besides, I already have a couple of questions/thoughts that are ill-fitted for github issues ^^ 

Common choices in this area are:

* Gitter (actix web https://github.com/actix/actix-web)
* Discord (tokio https://github.com/tokio-rs/tokio)
* Discourse (bors-ng https://github.com/bors-ng/bors-ng)
* Zullip (druid https://github.com/linebender/druid)

I personally have a strong preference towards Zulip or Discourse

**Comment by glommer** [comment] 2020-10-19 12:45
@sitano had already requested that.
I'm not against it, and I think that publishing this on crates(*), which I intend to do this week, is the perfect opportunity to signal that this is a good time.

(*) clearly marked as alpha. I have deliberated about it and decided the advantages of an early 0.1-alpha are enough to push.

I have never used anything in that list other than Discord.
Is slack an option? On the one hand I am more familiar with it, on the other hand slack sound gives me PTSD.

I will let other people comment on their choices for a while, but ultimately let's do it.
Aleksey, if you don't mind, why would you prefer the two you singled out ?

**Comment by sitano** [comment] 2020-10-19 12:49
Don't kill me but what about Mailing List? :+1:
Also for a real-time chat option we certainly need history search. In that sense Slack is not an option.

**Comment by glommer** [comment] 2020-10-19 12:57
Our list of contributors is so far small, so I will take the liberty to tag the majority of them (hope I don't forget any, if yes sorry in advance). If you have any argument to add to one solution vs the other I'll be leaving this open until Friday so we can decide.

At the end of the day technology is just a small part of what a community is and I am sure we can build a great place together!

@penberg 
@espindola 
@Daniel-B-Smith 
@HippoBaro 
@lukehoersten 
@sobolevn 
@teymour-aldridge 
@L1AN0

**Comment by glommer** [comment] 2020-10-19 13:03
@sitano I doubt any of those solutions would allow for keeping history without a premium plan.

**Comment by teymour-aldridge** [comment] 2020-10-19 13:03
Please not Gitter.

I like Zulip which I find to be the best platform for actually getting stuff done (Discord has historically had this "for gamers and gamers only" mindset so it's not perfect for project-related discussion, but it's a solid choice).

I think Discord will preserve infinite messages on the free plan, though I may be wrong.

**Comment by matklad** [comment] 2020-10-19 13:14
>Aleksey, if you don't mind, why would you prefer the two you singled out ?

There are three orthogonal categories of reasons why I like the two:

# Overall Brokenness

* when I used gitter couple of years ago, it was horribly broken
* Discord is slowish, logs me out if I hard-close the browser (and I hard-close browsers all the time) and (no, this is not a joke), if you out-out of email notifications, there's not way to enable them back.
* Slack is oke-ish, but *typing* a message into the message box laggs horribly

* Zulip is in "just works" category. The mobile apps are pretty bad though, but I don't use them. 
* Discourse is a beautifully engineered piece of software which works flawlessly and proves that you can build non-broken things with JS. It's one of the things which make me keep faith in the whole software engineering field :-)

# Conversation Model

* Discord and Zulip are chat/room IRC sync mode. I don't really enjoy it, because I like to type longer messages, timezone difference between Europe, America and Aisia make sync communication awkward. 
* Slack is mostly sync, though side-threads are nice. 

* Discourse is basically a mailing list, but with a modern UX (and you can literary use it as a mail-list, I've herd that it's email integration is seamless). It is extremely good for thorough, long-term value async discussion. It works less good for ephemeral sync discussion. 
* Zulip is right in the middle. It has somewhat unusual threading model, which takes some time to get used to, but does fulfill both sync and async modes. I think it is just as good as Discord or Slack for sync discussion, and slightly worse than Discourse for async discussion.

# Familiarity

I use three instances of Zulip (Ferrous Systems, Rust lang, Salsa) and a bunch of Discourses (urlo, irlo, nixos, julia, borsng, trio). 



I'd rate Slack as better then gitter and Discord, but worse than Zulip and Discourse.

**Comment by duarten** [comment] 2020-10-19 16:25
Don't forget about GitHub Discussions.

**Comment by glommer** [comment] 2020-10-19 23:12
I did some research on this:
- Github Discussions seems like something that is enabled for the organization, not the project, so it is a no-go.
- Somebody on twitter suggested matrix.org, but I am ruling that out due to lack of native hosting.

Best two options are Zulip and Discord. My thoughts on them so far:

* Zulip boasts about how good their async support is for people in different time zones. I am a bit skeptical, to be honest. Maybe @matklad who was experience can comment more on this but my thoughts are : if a discussion picks up enough heat, you'll have tons of stuff to catch up with when you show up anyway. How good is that in practice?

* Zulip's biggest disadvantage is that the pro account is 7USD a month per user. They say that they can sometimes lift those charges for OSS projects, if we can, might be a good fit. Otherwise the free plan feels too limited.

* Discord is totally free an unlimited, their business model seem to be just charge people to buy status which I ain't doing, but hey... each to your own.

* On the other hand Discord does seem very targeted at gamers, and very real time oriented too.

**Comment by glommer** [comment] 2020-10-19 23:14
@matklad BTW, I consider a broken app a feature, not a bug.

When not in the computer, people should be enjoying life.

**Comment by espindola** [comment] 2020-10-20 00:17
Glauber Costa <notifications@github.com> writes:

> Our list of contributors is so far small, so I will take the liberty to tag the majority of them (hope I don't forget any, if yes sorry in advance). If you have any argument to add to one solution vs the other I'll be leaving this open until Friday so we can decide.
>
> At the end of the day technology is just a small part of what a community is and I am sure we can build a great place together!
>
> @penberg 
> @espindola 

My preference is for anything with an open source client that doesn't
require running a browser. The ones I know are email and IRC, but I
don't expect that to be super popular.

Cheers,
Rafael

**Comment by duarten** [comment] 2020-10-20 03:30
(Github discussion can be enabled per repo afaik.)

**Comment by glommer** [comment] 2020-10-20 12:21
I found nothing of the sort in the settings, and the documentation I found is usually about how to enable it on an org. Maybe it can be set up per repo, once the organization has enabled it ?

**Comment by duarten** [comment] 2020-10-20 15:00
It's still in beta and being activated for some open source repositories; I don't have first-hand experience setting it up though. I just like that it's a sort of internal stackoverflow (e.g., https://github.com/vercel/next.js/discussions), searchable and persistent, but it would mean waiting until it's activated for this repo or made generally available.

**Comment by glommer** [comment] 2020-10-21 12:41
An update on this.

I spoke with folks from Zulip and we would qualify for their OSS project free usage tier (meaning we'd have full history, and the perks on the standard plan). With this, the biggest disadvantage of Zulip is gone.

From what I saw so far I liked Zulip. I like the idea of having something that can be used for real time communications and if it really does work well for async that is most definitely a plus.

Unless there is strong objection I'll be moving forward with it early tomorrow.

**Comment by sitano** [comment] 2020-10-21 12:59
@glommer Cool! What about group-wise async communication? Would be using Zulip also or Google Group (mailing lsts)?

**Comment by glommer** [comment] 2020-10-21 13:02
For now let's see if Zulip can handle everything. Aleksey claims that their async is good (although worse than the alternatives that focus on just that).

If it is a good mix between sync and async we'll not need anything else. Otherwise we'll revisit.

**Comment by sitano** [comment] 2020-10-21 13:31
Don't forget to send invites ;)

**Comment by glommer** [comment] 2020-10-22 02:18
Zulip is now active.

You can join with the link https://scipio.zulipchat.com/join/5gwim5jh2ghvrzqxztal5e4o/

I will leave the issue marked as open until I get confirmation we got upgraded to the full account, just in case.

**Closed** 2020-10-22 13:07 UTC

**Comment by matklad** [comment] 2020-10-22 13:16
Adding Zulip link to the readme might be useful ;)

**Comment by glommer** [comment] 2020-10-22 13:24
Is the link stable or would it expire? Slack invitations link are infamous for expiring on you.

**Comment by matklad** [comment] 2020-10-22 13:26
I think you need just https://scipio.zulipchat.com ? Zulip doesn't require
a special invite link as far as I know.

**Comment by glommer** [comment] 2020-10-22 13:27
good to know. I'll patch the `README` now. I noticed also that some of our examples in the `README` are outdated. Too bad Cargo can't compile them

**Comment by matklad** [comment] 2020-10-22 13:32
Well, there's https://github.com/livioribeiro/cargo-readme that is supposed
to help here.

But I personally prefer to keep README really short, and just link the main
page of the docs, which I use as a "real" readme:

* https://github.com/matklad/xshell, links to
* https://docs.rs/xshell/0.1.6/xshell/

**Comment by glommer** [comment] 2020-10-22 13:38
Of course there is Cargo-something for that. How naive of me to think there wasn't a crate for that =)

Coincidentally yesterday I was thinking the same thing after seeing the final Readme rendered: that we should maybe keep it short and move most of it somewhere else.

You know what... why do it later. Let's do it now!
